language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  pip install flake8 coveralls
before_script:
  flake8
script:
  coverage run --source=clickhouse_sqlalchemy setup.py test
after_success:
  coveralls
